spring:
  application:
    name: gateway  # The name of your Gateway application
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Disable discovery locator since routes are defined manually
      routes:
        - id: vendor-service
          uri: lb://VENDOR-SERVICE  # Use lb:// for load balancing with Eureka
          predicates:
            - Path=/api/vendors/**  # Routes /api/vendors/** to vendor-service
          
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
            - Path=/api/categories/**
            - Path=/api/reviews/**  # Routes /api/reviews/** to product-service
          
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
            - Path=/api/order-items/**  # Routes /api/order-items/** to order-service
          
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**  # Routes /auth/** to auth-service
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5005/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
   
server:
  port: 8083  # The port on which the gateway will run
